In [54]:
#https://www.kaggle.com/python10pm/learn-numpy-the-hard-way-70-exercises-solutions

<b> 1. How to import Numpy and see the version 

In [1]:
import numpy as np
print(np.__version__)

1.16.2


<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2. How to create an Array </b>    
<p><li> With the arange function:  </p>

In [88]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<li> Manually

In [89]:
arr2 = np.array([[9,2,5,4],[3,6,10,8],[2,10,7,6]])
arr2

array([[ 9,  2,  5,  4],
       [ 3,  6, 10,  8],
       [ 2, 10,  7,  6]])

<li> Special Arrays

In [80]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# identity matrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [84]:
np.repeat(5,9).reshape(3,3)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [85]:
np.tile([1,2,3],3).reshape(3,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

<li> Random Array in the half-open interval [0.0, 1.0)

In [86]:
np.random.rand(3,3)

array([[0.214593  , 0.42909072, 0.47651647],
       [0.21801533, 0.04282982, 0.35043136],
       [0.50744029, 0.8392992 , 0.01351834]])

<li> Random Normal Distribution Array (more at the numpy.random module)

In [87]:
np.random.randn(3,3)

array([[-0.86651193, -0.68562591,  0.99720643],
       [-1.40230661, -0.48788457, -2.16455771],
       [ 0.26125503,  0.30613247,  1.51594921]])

<li> Array of random integers between an upper bound and a lower bound

In [68]:
# dtype =low 'l' (inclusive)/ high 'h' (exclusive)
np.random.randint(4,12,(3,3),dtype='l')

array([[11,  7,  5],
       [ 7, 10,  7],
       [ 8,  8,  7]])

<li> Array from a uniformly distributed sample

In [75]:
np.random.uniform(4,12,(3,3))

array([[10.894,  9.399,  9.17 ],
       [ 5.863,  7.289,  5.916],
       [ 7.029,  5.526,  6.314]])

<li> Creating an array by specifing the minimum value, maximum value and number of elements

In [15]:
np.linspace(0,12,7)

array([ 0.,  2.,  4.,  6.,  8., 10., 12.])

<li> Generating a sequence using an input array

In [9]:
arr = np.array([1,2,3])
np.hstack((np.repeat(arr,3),np.tile(arr,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3. Array Properties </b>

In [20]:
# shape of an array
arr = np.array([[1,2,3]])
arr.shape

(1, 3)

In [22]:
# Dimension of an array
arr = np.array(4)
arr.ndim

0

In [23]:
# Type of an array
arr.dtype

dtype('int32')

In [91]:
arr1.min()

1

In [92]:
arr1.max()

12

In [101]:
arr1.sum()

78

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4. Array Operations:</b>
<p><li> Addition </p>

In [31]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.array([[9,2,5,4],[3,6,10,8],[2,10,7,6]])
np.add(arr1,arr2)

array([[10,  4,  8,  8],
       [ 8, 12, 17, 16],
       [11, 20, 18, 18]])

<li> Transpose

In [33]:
arr3 = arr2.T
print(arr3)

[[ 9  3  2]
 [ 2  6 10]
 [ 5 10  7]
 [ 4  8  6]]


<li> Dot Product (matrix multiplication)

In [34]:
np.dot(arr1,arr3)

array([[ 44,  77,  67],
       [124, 185, 167],
       [204, 293, 267]])

In [35]:
# Matrices VS 2D Arrays:
# 2D arrays behave in most aspects like a matrix. Yet, we can have "real" matrices in Numpy. They are a subset of the 2D arrays.
# The main difference shows, if you multiply two 2D arrays or two matrices. 
# We get real matrix multiplication by multiplying two matrices, but the 2D arrays will be only multiplied component-wise:
A = np.mat(arr1)
B = np.mat(arr3)
A*B

matrix([[ 44,  77,  67],
        [124, 185, 167],
        [204, 293, 267]])

<li> Maximum/Minimum of two arrays </li>
    <p> gives an array with the max/min of each value from 2 arrays </p>

In [106]:
max_arrays = np.maximum(arr1,arr2)
min_arrays = np.minimum(arr1,arr2)
# 
print("max(arr1,arr2):\n",max_arrays)
print("min(arr1,arr2):\n",min_arrays)

max(arr1,arr2):
 [[ 9  2  5  4]
 [ 5  6 10  8]
 [ 9 10 11 12]]
min(arr1,arr2):
 [[ 1  2  3  4]
 [ 3  6  7  8]
 [ 2 10  7  6]]


<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
5. Universal Functions </b>
<p><li> Square Root of an Array </p>

In [108]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

<li> Exponential of an Array

In [109]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
6. Numpy Where </b>
<p><li> Example 1: Make an array C where we choose the A value if the condition is True, otherwise we choose the B value </p>

In [64]:
A = np.array(3*[3*[100]])
print(A,'\n')

B = np.array(3*[3*[-99]])
print(B,'\n')

condition = np.array([[1,0,0],[0,1,0],[0,0,1]])

C = np.where(condition,A,B)
print(C,'\n')

[[100 100 100]
 [100 100 100]
 [100 100 100]] 

[[-99 -99 -99]
 [-99 -99 -99]
 [-99 -99 -99]] 

[[100 -99 -99]
 [-99 100 -99]
 [-99 -99 100]] 



<li> Example 2: Replace all the negative values in an array with 0</p>

In [110]:
D = np.array([[-1,3,-7],[6,-8,4],[9,-2,-5]])
C = np.where(D<0,0,D)
print(C)

[[0 3 0]
 [6 0 4]
 [9 0 0]]


<li> Example 3: Get the positions where arrays A and B match

In [41]:
A = np.array([2,6,6,7,9])
B = np.array([1,6,8,7,2])
C = np.where(A == B)
print(C)

(array([1, 3], dtype=int64),)


<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
7. Extract/Replace items that satisfy a given condition </b>
<p><li> Example 1: Extract all odd values from an array </p>

In [113]:
arr = np.array([0,-1,2,-3,4,5,6,-7,8,9,-10],dtype=float)
arr[arr%2==1]

array([-1., -3.,  5., -7.,  9.])

<li> Example 2: Replace negative items in an array with a non-type

In [114]:
arr[arr<0] = np.nan
print(arr)

[ 0. nan  2. nan  4.  5.  6. nan  8.  9. nan]


<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
8. Stacking two arrays </b>
<p><li> Vertically</p>

In [22]:
# Method 1
a = np.arange(10).reshape(2,5)
print(a)
b = np.repeat(1,10).reshape(2,5)
print(b)

np.concatenate((a,b),axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# Method 2
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
# Method 3 (r_ from row = combine rows)
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<li> Horizontally

In [27]:
# Method 1
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [28]:
# Method 2
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [29]:
# Method 3 (c_ from column = combine columns)
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
10. Array Indexing and Slicing

In [65]:
# Basic Slicing and Indexing
arr = np.arange(10)

In [69]:
# slicing an array
arr[3:9]

array([3, 4, 5, 6, 7, 8])

In [71]:
# slicing with a step
arr[3:9:2]

array([3, 5, 7])

In [25]:
# slicing with a step
a = np.arange(36).reshape(6,6)
print(a)
a[::3,::2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  2,  4],
       [18, 20, 22]])

In [26]:
a[::,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [68]:
# reverse the order of an array
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
#boolean indexing
arr[(arr>3) & (arr<7)]

array([4, 5, 6])

In [76]:
a[(a >= 5) & (a <= 10)]

array([5, 6])

In [15]:
# return the indices of elements that are not zero
arr = np.array([0,5,0,3,2,0,9])
print(np.nonzero(arr))

# ditching the zeros:
arr = arr[arr.nonzero()]
arr

(array([1, 3, 4, 6], dtype=int64),)


array([5, 3, 2, 9])

In [17]:
# np.nonzero can be used to return the indices where a condition is true
arr = np.array([12,65,32,43,96,110])
print(arr>60)
print(np.nonzero(arr>60))

[False  True False False  True  True]
(array([1, 4, 5], dtype=int64),)


In [3]:
# list indexing
arr = np.array([7,8,2,5,9,2,1])
arr[[0,3,4]]

array([7, 5, 9])

In [6]:
# Fancy indexing
arr1 = np.array([12,65,32,43,96,110])
arr2 = np.array([3,4,8,7,6,9])
arr2[arr1>60]

array([4, 6, 9])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
11. Manipulating array shape/rows/colums

In [30]:
# convert a 1D array to a 2D array with 2 rows
# -1 lets python figure out the other dimension on its own
arr = np.arange(0,12)
arr.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [17]:
# convert a 1D array to a 2D array with 3 columns
arr.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
# Swap two columns in a 2D array
arr = np.arange(0,9).reshape(3,3)
temp = arr[:,0].copy()
arr[:,0] = arr[:,1]
arr[:,1] = temp
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [65]:
# Reverse the columns of a 2D array
arr = np.arange(0,9).reshape(3,3)
print(arr)
arr[::-1,:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [66]:
# Reverse the rows of a 2D array
arr = np.arange(0,9).reshape(3,3)
print(arr)
arr[:,::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [68]:
# Flattening an array:
arr = np.arange(0,9).reshape(3,3)
# row-wise
arr.flatten()
# column-wise
arr.flatten(order='F')

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [80]:
# another way to do it
arr = arr.ravel()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
# Adding a new dimension
arr = arr[:,np.newaxis]
print(arr)
print(arr.ndim,arr.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
2 (9, 1)


In [65]:
arr[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
12. Printing Arrays

In [74]:
# How to set print options of an Array (to 3 decimals):
arr = np.random.random((3,3))
np.set_printoptions(3)
arr

array([[0.546, 0.849, 0.974],
       [0.547, 0.202, 0.403],
       [0.836, 0.576, 0.363]])

In [79]:
# How to suppress the scientific notation:
arr = np.random.random((3,3))/1e3
np.set_printoptions(7,suppress=True)
arr

array([[0.0000968, 0.0008005, 0.0005334],
       [0.0004177, 0.00026  , 0.0009648],
       [0.0008739, 0.0002578, 0.0002191]])

In [86]:
# Specify the maximum elements in an array which will trigger printing summarization (10 elements in this case)
arr = np.arange(1,51)
np.set_printoptions(threshold=10)
arr

array([ 1,  2,  3, ..., 48, 49, 50])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
13. Array Statistics

In [94]:
arr1.mean()

6.5

In [93]:
arr1.std()

3.452052529534663

In [6]:
# Finding a correlation between 2 columns:
#T his function computes the correlation as generally defined in signal processing texts::
# c_{av}[k] = sum_n a[n+k] * conj(v[n])
arr = np.array([[1,2,5],[3,6,7],[4,8,2]])
print(arr)
np.correlate(arr[:,0],arr[:,1])

[[1 2 5]
 [3 6 7]
 [4 8 2]]


array([52])

In [10]:
# Pearson correlation
np.corrcoef(arr[:,0],arr[:,1])

array([[1., 1.],
       [1., 1.]])

In [3]:
# Find the percentile of an array
arr = np.random.randn(100)
np.percentile(arr,q=[25,50,75])

array([-0.5301078 ,  0.02793523,  0.51438926])

In [6]:
# Generate a random sample from a given 1D array (with or without replacement)
# we can create weighted choices by using p = []
arr = np.arange(100)
np.random.choice(arr,size=3)

array([68, 27, 51])

In [83]:
# The function random_sample returns random floats in the interval [0.0, 1.0) from the "continuous uniform" distribution
# create arrays with values from interval [a,b) with: (b - a) * random_sample() + a
np.random.random_sample(10)

array([0.59445511, 0.92594135, 0.27299581, 0.15329192, 0.15317222,
       0.01174131, 0.47266753, 0.78987296, 0.14817155, 0.43438637])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14. Common Items in Arrays

In [54]:
# Get the common items in the same position in 2 arrays
arr1 = np.array([3,4,8,9,3,2])
arr2 = np.array([5,9,8,2,6,2])
# by returning their count and index
np.unique(arr1[arr1==arr2],return_index=True,return_counts=True)

(array([2, 8]), array([1, 0], dtype=int64), array([1, 1], dtype=int64))

In [24]:
# Get the common items in two arrays regardless of their position
arr1[np.isin(arr1,arr2)]

array([8, 9, 2])

In [46]:
# Remove from arr1 the elements that exist in arr2
arr1 = np.array([1,7,3,4,8,9,3,2])
arr2 = np.array([5,9,8,2])

arr1[~np.isin(arr1,arr2)]

array([1, 7, 3, 4, 3])

In [47]:
# Unique elements in one array
arr = np.array([[1,1,3,1],[5,6,6,7],[0,0,0,8]]).T
print(arr)
np.unique(arr,return_counts=True)

[[1 5 0]
 [1 6 0]
 [3 6 0]
 [1 7 8]]


(array([0, 1, 3, 5, 6, 7, 8]), array([3, 3, 1, 1, 2, 1, 1], dtype=int64))

In [48]:
# Finding if two arrays are equal:
np.array_equal(arr1,arr2)

False

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
15. Missing Values in Arrays (NaN)

In [4]:
# Find the position of missing values in an array
arr = np.array([[1,4,np.nan],[8,9,4],[5,np.nan,7]])
print(arr)
np.where(np.isnan(arr))

[[ 1.  4. nan]
 [ 8.  9.  4.]
 [ 5. nan  7.]]


(array([0, 2], dtype=int64), array([2, 1], dtype=int64))

In [5]:
# WARNING! Super duper clumsy code
# remove the rows that contain non values
nan_rows = np.where(np.isnan(arr))[:][:][0]
nonnan_rows = [i for i in range(arr.shape[0]) if i not in nan_rows]
new_arr = arr[nonnan_rows,:]
new_arr

array([[8., 9., 4.]])

In [6]:
# remove the columns that contain non values
nan_cols = np.where(np.isnan(arr))[:][:][1]
nonnan_cols = [i for i in range(arr.shape[1]) if i not in nan_cols]
new_arr = arr[:,nonnan_cols]
new_arr

array([[1.],
       [8.],
       [5.]])

In [7]:
# MUCH MUCH More elegant solution:
# remove the rows that contain non values
arr[np.sum(np.isnan(arr), axis = 1) == 0]

array([[8., 9., 4.]])

In [8]:
# remove the columns that contain non values
arr[:,np.sum(np.isnan(arr), axis = 0) == 0]

array([[1.],
       [8.],
       [5.]])

In [47]:
# Find if a given array has any null values:
arr = np.array([[1,4,np.nan],[8,9,4],[5,np.nan,7]])
print(np.any(np.isnan(arr)))

# Find how many nan values:
print(np.isnan(arr).sum())

# Replace all nan values with 0 (in a copy array):
np.where(np.isnan(arr),0,arr)

True
2


array([[1., 4., 0.],
       [8., 9., 4.],
       [5., 0., 7.]])

In [48]:
# 2nd way: (the advantage of this is that NaN can be replaced with anything)
arr[np.isnan(arr)] = 0
arr

array([[1., 4., 0.],
       [8., 9., 4.],
       [5., 0., 7.]])

In [44]:
# Other way to replace all nan values with zero (in place):
arr = np.array([[1,4,np.nan],[8,9,4],[5,np.nan,7]])
np.nan_to_num(arr,copy=False)

array([[1., 4., 0.],
       [8., 9., 4.],
       [5., 0., 7.]])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
16. Sorting Arrays

In [44]:
# Sorting the elements of an array row-wise (axis = -1 bu default)
# column-wise (axis = 0)
arr = np.array([[9,2,5,4],[3,6,10,8],[2,10,7,6]])
arr.sort(axis=-1)
arr

array([[ 2,  4,  5,  9],
       [ 3,  6,  8, 10],
       [ 2,  6,  7, 10]])

In [9]:
# Find the indices into a sorted array `a` such that, if the corresponding elements in `v` were inserted before the indices, the order of `a` would be preserved.
np.searchsorted([1,18,29,33,87,91],[15,32])

array([1, 3], dtype=int64)

In [10]:
# Return the indices that would sort the array
arr = np.array([1,5,3,2,8,7])
arr.argsort()

array([0, 3, 2, 1, 5, 4], dtype=int64)

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
17. Copying Arrays

In [30]:
# Check if two numpy objects share the same memory:
A = np.arange(15).reshape(5,3)
B = A[::,1:]
np.may_share_memory(A,B)

True

In [32]:
C = A.copy()
np.may_share_memory(A,C)

False

In [26]:
# Making a copy of an array:
# when making a copy the default order layout of the copy is C-order
# an array is a C contiguous when the rows are stored as contiguous blocks of memory. 
# a C- Contiguous array has slightly faster row operations.
# arr.T is Fortran contiguous since the columns are in contiguous blocks of memory. 
# in an F-Contiguous array, column operations are faster
# When making a copy of an array, the default is C-contiguous:
arr1 = np.array([[1,4,5],[7,3,9]], order='F')
arr2 = arr1.copy()

print(arr1.flags['C_CONTIGUOUS'])
print(arr2.flags['C_CONTIGUOUS'])

False
True


<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
18. Data Type Objects, dtype

In [23]:
# the dtype object is an instance of numpy.dtype class
# numpy arrays created with the above shown methods contain homogenous data types such as int and float
# we can create "structured arrays" with different data types per column

dt = np.dtype([('Country','U20'),('Density','i4'),('Monarchy','?'),('Population','i4')])

In [25]:
# we have to define the array with tuples, not lists
a = np.array([('France',111,False,63601002),
              ('Morocco',81,True,40000000),
              ('UK',256,True,62262000)],dtype=dt)
a

array([('France', 111, False, 63601002),
       ('Morocco',  81,  True, 40000000), ('UK', 256,  True, 62262000)],
      dtype=[('Country', '<U20'), ('Density', '<i4'), ('Monarchy', '?'), ('Population', '<i4')])

In [22]:
# accessing the columns:
a['Country']

array(['France', 'Morocco', 'UK'], dtype='<U20')

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
19. Reading and Writing Data Files

In [9]:
# saving text files
arr = np.arange(9).reshape(3,3)
np.savetxt("array1.txt",arr,fmt="%2.3f",delimiter=",")
np.savetxt("array2.txt",arr,fmt="%4d",delimiter="/",newline='\n',header='',footer='')

In [13]:
# loading text files
np.loadtxt("array1.txt",delimiter=',')

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [17]:
# choose the columns to load
np.loadtxt("array2.txt",delimiter="/",usecols=(0,1))

array([[0., 1.],
       [3., 4.],
       [6., 7.]])

In [34]:
#??????????????????????????????????????????
# Recommended way to store and load data with Numpy in Python is "load" and "aave"
from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(10)
np.save(outfile,x)
outfile.seek(0) #to simulate closing and opening the file
np.load(outfile)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# genfromtxt: another way to read files which can process archive files as well (gzip, bzip2)
# slower than loadtxt, but can cope with missing data and fill them
np.genfromtxt("array1.txt",dtype='i4',delimiter=',',missing_values=None,filling_values=None)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<b>------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Hacks

In [77]:
# Using a python scalars function on an array
arr1 = np.array([1,7,3,4,8,9,3,2])
arr2 = np.array([5,9,8,2])
np.array([max(a,b) for a,b in zip(arr1,arr2)])

array([5, 9, 8, 4])

In [88]:
# turning array elements into a string
arr = np.arange(9).reshape(3,3)
np.array([str(arr[i,j]) for i in range(arr.shape[0]) for j in range(arr.shape[1])]).reshape(arr.shape)

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U1')

In [20]:
# Finding the most frequent element in a Numpy array
a = np.array([0,3,4,4,4,3,3,3,3,0,0,3,3,4])
vals, counts = np.unique(a,return_counts=True)
frequent_value = vals[counts.argmax()]
print(frequent_value)

3


In [26]:
# Finding the indices of numbers larger than a certain value in an array
a = np.array([4,3,6,8,8,11,16,9,2])
np.argwhere(a > 10)
# finding the 1st occurence:
np.argwhere(a > 10)[0]

array([5], dtype=int64)

In [7]:
# Advantage of Numpy is that it's faster than python and numpy objects take less memory space
size_of_vec = 1000
%%timeit
X = range(size_of_vec)
Y = range(size_of_vec)
Z = [X[i] + Y[i] for i in range(len(X)) ]

266 µs ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%%timeit
X = np.arange(size_of_vec)
Y = np.arange(size_of_vec)
Z = X + Y

3.48 µs ± 76.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
# Find the primes numbers between 0 and 100
is_prime = np.ones((100,),dtype=bool)
# cross out 0 and 1 which are not primes
is_prime[:2] = 0
# cross out its higher multiples (sieve of Eratosthenes):
nmax = int(np.sqrt(len(is_prime)))
for i in range(2,nmax):
    # start at 2*i, with a step of i, til the end if the list
    # gives us all multiples of i except for i
    is_prime[2*i::i] = False
    
print(np.nonzero(is_prime))

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97], dtype=int64),)


In [35]:
1%5

1